image: commandemy/ansible-cicd:latest

services:
  - docker:19.03.1-dind

before_script:
  - ansible --version
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - export ANSIBLE_CONFIG=ansible.cfg


build:
  stage: test
  script:
    - ansible hosts -m ping
