image: commandemy/ansible-cicd:latest

services:
  - docker:19.03.1-dind

before_script:
  - export ANSIBLE_CONFIG=ansible.cfg
  - ansible --version
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - /usr/bin/git --version


build:
  stage: test
  script:
    - mkdir roles
#    - git clone git@gitlab.commandemy.training:git_training_user_20/helloworld.git roles/helloworld
    - ansible-galaxy install -vvv --force -r requirements.yml
    - ansible-playbook loadbalancer.yml
